image: berenger/spetabaruci

dagpar-simple:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++-7 cmake ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test

dagpar-advanced:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++-7 cmake .. -DDAGPAR_USE_ACYCLIC=ON
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test

dagpar-debug-coverage:
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=DEBUG -DDAGPAR_USE_COVERAGE=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - lcov --directory ./ -c -o coverage-rapport.info
    - lcov --list coverage-rapport.info
    - genhtml -o ../coverage -t "Coverage example" coverage-rapport.info
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - dagpar-debug-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

